const referenceData = [
  {
    name: 'STRING',
    type: 'Command',
    desc: 'Types the given text using the active keyboard layout.',
    example: 'STRING Hello World!\nSTRING notepad.exe',
  },
  {
    name: 'STRINGLN',
    type: 'Command',
    desc: 'Types text and then presses Enter.',
    example: 'STRINGLN echo OverQuack is ready',
  },
  {
    name: 'DELAY',
    type: 'Command',
    desc: 'Pauses execution for a specified number of milliseconds.',
    example: 'DELAY 1000\nSTRING waited 1 second',
  },
  {
    name: 'DEFAULT_DELAY',
    type: 'Command',
    desc: 'Sets a default delay between every payload line (in ms).',
    example: 'DEFAULT_DELAY 50\nSTRING fast\nSTRING also fast',
  },
  {
    name: 'RANDOM_DELAY',
    type: 'Command',
    desc: 'Sleeps for a random number of milliseconds between min and max.',
    example: 'RANDOM_DELAY 100 500\nSTRING unpredictable timing',
  },
  {
    name: 'ENTER',
    type: 'Command',
    desc: 'Presses the Enter / Return key.',
    example: 'STRING notepad\nENTER',
  },
  {
    name: 'SPACE',
    type: 'Command',
    desc: 'Presses the Space bar.',
    example: 'STRING Hello\nSPACE\nSTRING World',
  },
  {
    name: 'TAB',
    type: 'Command',
    desc: 'Presses the Tab key.',
    example: 'STRING username\nTAB\nSTRING password',
  },
  {
    name: 'BACKSPACE',
    type: 'Command',
    desc: 'Presses the Backspace key.',
    example: 'STRING Helloo\nBACKSPACE',
  },
  {
    name: 'ESC',
    type: 'Command',
    desc: 'Presses the Escape key.',
    example: 'ESC',
  },
  {
    name: 'INSERT',
    type: 'Command',
    desc: 'Presses the Insert key.',
    example: 'INSERT',
  },
  {
    name: 'DELETE',
    type: 'Command',
    desc: 'Presses the Delete key.',
    example: 'SHIFT END\nDELETE',
  },
  {
    name: 'HOME',
    type: 'Command',
    desc: 'Presses the Home key.',
    example: 'HOME\nSHIFT END\nDELETE',
  },
  {
    name: 'END',
    type: 'Command',
    desc: 'Presses the End key.',
    example: 'END',
  },
  {
    name: 'PAGEUP',
    type: 'Command',
    desc: 'Presses the Page Up key.',
    example: 'PAGEUP',
  },
  {
    name: 'PAGEDOWN',
    type: 'Command',
    desc: 'Presses the Page Down key.',
    example: 'PAGEDOWN',
  },
  {
    name: 'UPARROW',
    type: 'Command',
    desc: 'Up arrow key.',
    example: 'UPARROW\nUPARROW\nUPARROW',
  },
  {
    name: 'DOWNARROW',
    type: 'Command',
    desc: 'Down arrow key.',
    example: 'DOWNARROW\nDOWNARROW',
  },
  {
    name: 'LEFTARROW',
    type: 'Command',
    desc: 'Left arrow key.',
    example: 'LEFTARROW\nLEFTARROW',
  },
  {
    name: 'RIGHTARROW',
    type: 'Command',
    desc: 'Right arrow key.',
    example: 'RIGHTARROW\nRIGHTARROW',
  },
  { name: 'UP', type: 'Command', desc: 'Alias for UPARROW.', example: 'UP' },
  {
    name: 'DOWN',
    type: 'Command',
    desc: 'Alias for DOWNARROW.',
    example: 'DOWN',
  },
  {
    name: 'LEFT',
    type: 'Command',
    desc: 'Alias for LEFTARROW.',
    example: 'LEFT',
  },
  {
    name: 'RIGHT',
    type: 'Command',
    desc: 'Alias for RIGHTARROW.',
    example: 'RIGHT',
  },
  {
    name: 'PRINTSCREEN',
    type: 'Command',
    desc: 'Print Screen key.',
    example: 'PRINTSCREEN',
  },
  {
    name: 'PAUSE',
    type: 'Command',
    desc: 'Pause / Break key.',
    example: 'PAUSE',
  },
  { name: 'BREAK', type: 'Command', desc: 'Same as PAUSE.', example: 'BREAK' },
  {
    name: 'CAPSLOCK',
    type: 'Command',
    desc: 'Toggles Caps Lock on/off.',
    example:
      'IF ($_CAPSLOCK_ON == 1)\n    PRINT Caps is ON\nELSE\n    PRINT Caps is OFF\nEND_IF',
  },
  {
    name: 'NUMLOCK',
    type: 'Command',
    desc: 'Toggles Num Lock on/off.',
    example: 'IF ($_NUMLOCK_ON == 0)\n    NUMLOCK\nEND_IF',
  },
  {
    name: 'SCROLLLOCK',
    type: 'Command',
    desc: 'Toggles Scroll Lock on/off.',
    example: 'SCROLLLOCK',
  },
  {
    name: 'GUI',
    type: 'Command',
    desc: 'Presses the Windows / Command key.',
    example: 'GUI r\nDELAY 500\nSTRING cmd\nENTER',
  },
  {
    name: 'WINDOWS',
    type: 'Command',
    desc: 'Same as GUI.',
    example: 'WINDOWS d',
  },
  {
    name: 'COMMAND',
    type: 'Command',
    desc: 'Mac Command key (same as GUI).',
    example: 'COMMAND space',
  },
  { name: 'RGUI', type: 'Command', desc: 'Right GUI key.', example: 'RGUI' },
  {
    name: 'RWINDOWS',
    type: 'Command',
    desc: 'Right Windows key.',
    example: 'RWINDOWS',
  },
  {
    name: 'RCOMMAND',
    type: 'Command',
    desc: 'Right Command key.',
    example: 'RCOMMAND',
  },
  {
    name: 'ALT',
    type: 'Command',
    desc: 'Presses the Alt key.',
    example: 'ALT F4\nALT TAB',
  },
  { name: 'RALT', type: 'Command', desc: 'Right Alt key.', example: 'RALT' },
  {
    name: 'OPTION',
    type: 'Command',
    desc: 'Mac Option key (same as ALT).',
    example: 'OPTION',
  },
  {
    name: 'ROPTION',
    type: 'Command',
    desc: 'Right Option key.',
    example: 'ROPTION',
  },
  {
    name: 'CTRL',
    type: 'Command',
    desc: 'Presses the Ctrl (Control) key.',
    example: 'CTRL c\nCTRL v',
  },
  {
    name: 'CONTROL',
    type: 'Command',
    desc: 'Same as CTRL.',
    example: 'CONTROL a',
  },
  { name: 'RCTRL', type: 'Command', desc: 'Right Ctrl key.', example: 'RCTRL' },
  {
    name: 'RIGHT_CONTROL',
    type: 'Command',
    desc: 'Right Control key (same as RCTRL).',
    example: 'RIGHT_CONTROL',
  },
  {
    name: 'SHIFT',
    type: 'Command',
    desc: 'Presses the Shift key.',
    example: 'SHIFT DELETE\nSHIFT HOME',
  },
  {
    name: 'RSHIFT',
    type: 'Command',
    desc: 'Right Shift key.',
    example: 'RSHIFT',
  },
  {
    name: 'APP',
    type: 'Command',
    desc: 'Application / Context menu key.',
    example: 'APP',
  },
  { name: 'MENU', type: 'Command', desc: 'Same as APP.', example: 'MENU' },

  { name: 'F1', type: 'Command', desc: 'Function key F1.', example: 'F1' },
  { name: 'F2', type: 'Command', desc: 'Function key F2.', example: 'F2' },
  { name: 'F3', type: 'Command', desc: 'Function key F3.', example: 'F3' },
  { name: 'F4', type: 'Command', desc: 'Function key F4.', example: 'F4' },
  { name: 'F5', type: 'Command', desc: 'Function key F5.', example: 'F5' },
  { name: 'F6', type: 'Command', desc: 'Function key F6.', example: 'F6' },
  { name: 'F7', type: 'Command', desc: 'Function key F7.', example: 'F7' },
  { name: 'F8', type: 'Command', desc: 'Function key F8.', example: 'F8' },
  { name: 'F9', type: 'Command', desc: 'Function key F9.', example: 'F9' },
  { name: 'F10', type: 'Command', desc: 'Function key F10.', example: 'F10' },
  { name: 'F11', type: 'Command', desc: 'Function key F11.', example: 'F11' },
  { name: 'F12', type: 'Command', desc: 'Function key F12.', example: 'F12' },
  { name: 'F13', type: 'Command', desc: 'Function key F13.', example: 'F13' },
  { name: 'F14', type: 'Command', desc: 'Function key F14.', example: 'F14' },
  { name: 'F15', type: 'Command', desc: 'Function key F15.', example: 'F15' },
  { name: 'F16', type: 'Command', desc: 'Function key F16.', example: 'F16' },
  { name: 'F17', type: 'Command', desc: 'Function key F17.', example: 'F17' },
  { name: 'F18', type: 'Command', desc: 'Function key F18.', example: 'F18' },
  { name: 'F19', type: 'Command', desc: 'Function key F19.', example: 'F19' },
  { name: 'F20', type: 'Command', desc: 'Function key F20.', example: 'F20' },
  { name: 'F21', type: 'Command', desc: 'Function key F21.', example: 'F21' },
  { name: 'F22', type: 'Command', desc: 'Function key F22.', example: 'F22' },
  { name: 'F23', type: 'Command', desc: 'Function key F23.', example: 'F23' },
  { name: 'F24', type: 'Command', desc: 'Function key F24.', example: 'F24' },

  {
    name: 'MK_VOLUP',
    type: 'Command',
    desc: 'Volume up.',
    example: 'MK_VOLUP\nMK_VOLUP',
  },
  {
    name: 'MK_VOLDOWN',
    type: 'Command',
    desc: 'Volume down.',
    example: 'MK_VOLDOWN',
  },
  {
    name: 'MK_MUTE',
    type: 'Command',
    desc: 'Mute / unmute audio.',
    example: 'MK_MUTE',
  },
  { name: 'MK_NEXT', type: 'Command', desc: 'Next track.', example: 'MK_NEXT' },
  {
    name: 'MK_PREV',
    type: 'Command',
    desc: 'Previous track.',
    example: 'MK_PREV',
  },
  { name: 'MK_PP', type: 'Command', desc: 'Play / Pause.', example: 'MK_PP' },
  {
    name: 'MK_STOP',
    type: 'Command',
    desc: 'Stop playback.',
    example: 'MK_STOP',
  },

  {
    name: 'MOUSE_MOVE',
    type: 'Command',
    desc: 'Move mouse to absolute (x, y) coordinates.',
    example: 'MOUSE_MOVE 500 300\nDELAY 200\nMOUSE_CLICK LEFT',
  },
  {
    name: 'MOUSE_CLICK',
    type: 'Command',
    desc: 'Click a mouse button (LEFT, RIGHT, MIDDLE).',
    example: 'MOUSE_MOVE 200 200\nMOUSE_CLICK LEFT',
  },
  {
    name: 'MOUSE_PRESS',
    type: 'Command',
    desc: 'Hold down a mouse button.',
    example: 'MOUSE_PRESS LEFT\nMOUSE_MOVE 0 100\nMOUSE_RELEASE LEFT',
  },
  {
    name: 'MOUSE_RELEASE',
    type: 'Command',
    desc: 'Release a held mouse button.',
    example: 'MOUSE_RELEASE LEFT',
  },
  {
    name: 'MOUSE_SCROLL',
    type: 'Command',
    desc: 'Scroll the mouse wheel (positive = up, negative = down).',
    example: 'MOUSE_SCROLL 5\nDELAY 300\nMOUSE_SCROLL -3',
  },
  {
    name: 'JIGGLE_MOUSE',
    type: 'Command',
    desc: 'Jiggle the mouse pointer for a given duration (ms), step size, and sleep interval.',
    example: 'JIGGLE_MOUSE 2000 10 0.1',
  },
  {
    name: 'BACKGROUND_JIGGLE_MOUSE',
    type: 'Command',
    desc: 'Start a background mouse jiggle task (use INF for infinite, otherwise duration in ms).',
    example:
      'BACKGROUND_JIGGLE_MOUSE INF 5 0.2\nDELAY 5000\nSTRING still running...',
  },

  {
    name: 'HOLD',
    type: 'Command',
    desc: 'Hold down one or more keys. Use RELEASE to release them.',
    example: 'HOLD CTRL SHIFT\nDELAY 1000\nRELEASE CTRL SHIFT',
  },
  {
    name: 'RELEASE',
    type: 'Command',
    desc: 'Release previously held keys.',
    example: 'RELEASE CTRL SHIFT',
  },
  {
    name: 'RELEASE_ALL',
    type: 'Command',
    desc: 'Release every currently held key.',
    example: 'RELEASE_ALL',
  },

  {
    name: 'IF',
    type: 'Control',
    desc: 'Start an if block. Condition supports ==, !=, <, >, &&, ||.',
    example:
      'IF ($_CAPSLOCK_ON == 1)\n    PRINT Caps is ON\nELSE\n    PRINT Caps is OFF\nEND_IF',
  },
  {
    name: 'ELSE',
    type: 'Control',
    desc: 'Else branch.',
    example: 'IF $x == 10\n    PRINT ten\nELSE\n    PRINT not ten\nEND_IF',
  },
  {
    name: 'ELSEIF',
    type: 'Control',
    desc: 'Else if branch.',
    example:
      'IF $score >= 90\n    PRINT A\nELSEIF $score >= 80\n    PRINT B\nELSE\n    PRINT C\nEND_IF',
  },
  {
    name: 'END_IF',
    type: 'Control',
    desc: 'End of an if block.',
    example: 'END_IF',
  },
  {
    name: 'WHILE',
    type: 'Control',
    desc: 'Start a while loop.',
    example:
      'VAR $i = 0\nWHILE ($i < 3)\n    PRINT Count: $i\n    $i = $i + 1\nEND_WHILE',
  },
  {
    name: 'END_WHILE',
    type: 'Control',
    desc: 'End of a while loop.',
    example: 'END_WHILE',
  },
  {
    name: 'FUNCTION',
    type: 'Control',
    desc: 'Define a reusable function. Call it with name().',
    example:
      'FUNCTION openNotepad()\n    GUI r\n    DELAY 200\n    STRING notepad\n    ENTER\nEND_FUNCTION\nopenNotepad()',
  },
  {
    name: 'END_FUNCTION',
    type: 'Control',
    desc: 'End of a function definition.',
    example: 'END_FUNCTION',
  },
  {
    name: 'RESTART_PAYLOAD',
    type: 'Command',
    desc: 'Restart the current payload from the beginning.',
    example: 'RESTART_PAYLOAD',
  },
  {
    name: 'STOP_PAYLOAD',
    type: 'Command',
    desc: 'Stop execution completely.',
    example: 'STOP_PAYLOAD',
  },
  {
    name: 'REPEAT',
    type: 'Command',
    desc: 'Repeat the last N lines a given number of times.',
    example: 'STRING Hello\nENTER\nREPEAT LINES=2 TIMES=5',
  },
  {
    name: 'IMPORT',
    type: 'Command',
    desc: 'Execute another .oqs file inline (like including a sub-payload).',
    example: 'IMPORT common.oqs',
  },

  {
    name: 'VAR',
    type: 'Control',
    desc: 'Declare a mutable variable. Variables are expanded with $name.',
    example: 'VAR $username = "OverQuack"\nSTRING Hello $username',
  },
  {
    name: 'DEFINE',
    type: 'Control',
    desc: 'Create an immutable constant. Recommendeed to use @name for clarity, but you can use direct name as you want',
    example:
      'DEFINE @FAST 50\nDELAY @FAST\nSTRING @FAST\n// OR USE DIRECT NAME\nDEFINE MESSAGE "Dear Friend"\nSTRINGLN MESSAGE \n// i strongly recommend you to use @ in define to avoid any confusion or maybe any future language update :]',
  },
  {
    name: '$variable =',
    type: 'Control',
    desc: 'Assign a value to a variable (without VAR).',
    example: '$counter = 10\n$counter = $counter + 1',
  },

  {
    name: 'REM',
    type: 'Control',
    desc: 'Single-line comment.',
    example: 'REM this line is a comment',
  },
  {
    name: '//',
    type: 'Control',
    desc: 'Alternative single-line comment.',
    example: '// also a comment',
  },
  {
    name: 'REM_BLOCK … END_REM',
    type: 'Control',
    desc: 'Multi-line comment block.',
    example: 'REM_BLOCK\n  This whole section\n  is ignored\nEND_REM',
  },
  {
    name: '/* … */',
    type: 'Control',
    desc: 'C-style block comment.',
    example: '/* block comment */',
  },

  {
    name: 'STRING_BLOCK … END_STRING',
    type: 'Control',
    desc: 'Types multiple lines without Enter after each.',
    example: 'STRING_BLOCK\n  Line one\n  Line two\nEND_STRING',
  },
  {
    name: 'STRINGLN_BLOCK … END_STRINGLN',
    type: 'Control',
    desc: 'Types multiple lines, adding Enter after each.',
    example: 'STRINGLN_BLOCK\n  First line\n  Second line\nEND_STRINGLN',
  },
  {
    name: 'ENABLE_STRIP',
    type: 'Control',
    desc: 'Enable whitespace stripping inside string blocks.',
    example:
      'ENABLE_STRIP\nSTRING_BLOCK\n  leading spaces will be stripped\nEND_STRING',
  },
  {
    name: 'DISABLE_STRIP',
    type: 'Control',
    desc: 'Disable whitespace stripping inside string blocks.',
    example: 'DISABLE_STRIP',
  },

  {
    name: 'SELECT_LAYOUT',
    type: 'Command',
    desc: 'Switch keyboard layout at runtime. Must be one of the supported layouts.',
    example: 'SELECT_LAYOUT WIN_DE\nSTRING Hallo Welt',
  },

  {
    name: 'LED_ON',
    type: 'Command',
    desc: 'Turn the built-in LED on.',
    example: 'LED_ON\nDELAY 500\nLED_OFF',
  },
  {
    name: 'LED_OFF',
    type: 'Command',
    desc: 'Turn the built-in LED off.',
    example: 'LED_OFF',
  },
  {
    name: 'LED_R',
    type: 'Command',
    desc: "Alias for LED_ON (often red, but on a Pico it's just the onboard LED).",
    example: 'LED_R',
  },
  {
    name: 'LED_G',
    type: 'Command',
    desc: 'Alias for LED_ON (green).',
    example: 'LED_G',
  },

  {
    name: 'WAIT_FOR_CAPS_ON',
    type: 'Command',
    desc: 'Pause until Caps Lock is turned on.',
    example: 'WAIT_FOR_CAPS_ON\nPRINT Caps is now ON',
  },
  {
    name: 'WAIT_FOR_CAPS_OFF',
    type: 'Command',
    desc: 'Pause until Caps Lock is turned off.',
    example: 'WAIT_FOR_CAPS_OFF',
  },
  {
    name: 'WAIT_FOR_CAPS_CHANGE',
    type: 'Command',
    desc: 'Pause until Caps Lock toggles (any change).',
    example: 'WAIT_FOR_CAPS_CHANGE\nPRINT Caps state changed',
  },
  {
    name: 'WAIT_FOR_NUM_ON',
    type: 'Command',
    desc: 'Pause until Num Lock is turned on.',
    example: 'WAIT_FOR_NUM_ON',
  },
  {
    name: 'WAIT_FOR_NUM_OFF',
    type: 'Command',
    desc: 'Pause until Num Lock is turned off.',
    example: 'WAIT_FOR_NUM_OFF',
  },
  {
    name: 'WAIT_FOR_NUM_CHANGE',
    type: 'Command',
    desc: 'Pause until Num Lock toggles.',
    example: 'WAIT_FOR_NUM_CHANGE',
  },
  {
    name: 'WAIT_FOR_SCROLL_ON',
    type: 'Command',
    desc: 'Pause until Scroll Lock is turned on.',
    example: 'WAIT_FOR_SCROLL_ON',
  },
  {
    name: 'WAIT_FOR_SCROLL_OFF',
    type: 'Command',
    desc: 'Pause until Scroll Lock is turned off.',
    example: 'WAIT_FOR_SCROLL_OFF',
  },
  {
    name: 'WAIT_FOR_SCROLL_CHANGE',
    type: 'Command',
    desc: 'Pause until Scroll Lock toggles.',
    example: 'WAIT_FOR_SCROLL_CHANGE',
  },

  {
    name: 'ATTACKMODE',
    type: 'Command',
    desc: 'Switch USB personality and reboot. Options: HID, STORAGE, HID STORAGE. The payload resumes from the next line after reboot.',
    example:
      'REM Expose storage, reboot, and continue\nATTACKMODE HID STORAGE\nREM After reset, device will appear as keyboard + drive\n//or\nATTACKMODE HID\n',
  },
  {
    name: 'ATTACKMODE (HID only)',
    type: 'Command',
    desc: 'Only keyboard/mouse, no drive.',
    example: 'ATTACKMODE HID',
  },
  {
    name: 'RESET',
    type: 'Command',
    desc: 'Reboot the device in normal mode (reset and continue payload?). Actually it just resets the microcontroller.',
    example: 'RESET',
  },
  {
    name: 'RESET_SAFE',
    type: 'Command',
    desc: 'Reboot into safe mode (CircuitPython safe mode).',
    example: 'RESET_SAFE',
  },
  {
    name: 'RESET_UF2',
    type: 'Command',
    desc: 'Reboot into UF2 bootloader (for firmware updates).',
    example: 'RESET_UF2',
  },
  {
    name: 'SET_RESET_NORMAL',
    type: 'Command',
    desc: 'Set the next reset to normal mode (without rebooting now).',
    example: 'SET_RESET_NORMAL',
  },
  {
    name: 'SET_RESET_SAFE',
    type: 'Command',
    desc: 'Set the next reset to safe mode.',
    example: 'SET_RESET_SAFE',
  },
  {
    name: 'SET_RESET_UF2',
    type: 'Command',
    desc: 'Set the next reset to UF2 bootloader.',
    example: 'SET_RESET_UF2',
  },
  {
    name: 'FORMAT',
    type: 'Command',
    desc: 'Erase the entire filesystem and reboot.',
    example: 'FORMAT',
  },

  {
    name: 'PRINT',
    type: 'Command',
    desc: 'Print a message to the serial console (for debugging).',
    example: 'PRINT Starting stage 2...',
  },
  {
    name: 'ENABLE_DEBUG',
    type: 'Command',
    desc: 'Turn on verbose debug output on the serial port.',
    example: 'ENABLE_DEBUG',
  },
  {
    name: 'DISABLE_DEBUG',
    type: 'Command',
    desc: 'Turn off debug output.',
    example: 'DISABLE_DEBUG',
  },

  {
    name: '$_JITTER_ENABLED',
    type: 'System Variable',
    desc: 'Set to 1 to enable random micro-delays between lines.',
    example: '$_JITTER_ENABLED = 1\n$ $_JITTER_MAX = 30',
  },
  {
    name: '$_JITTER_MAX',
    type: 'System Variable',
    desc: 'Maximum extra jitter delay in milliseconds.',
    example: '$_JITTER_MAX = 50',
  },

  {
    name: '$_CAPSLOCK_ON',
    type: 'System Variable',
    desc: '1 if Caps Lock is on, otherwise 0.',
    example:
      'IF ($_CAPSLOCK_ON == 1)\n    PRINT Caps is ON\nELSE\n    PRINT Caps is OFF\nEND_IF',
  },

  {
    name: '$_NUMLOCK_ON',
    type: 'System Variable',
    desc: '1 if Num Lock is on, otherwise 0.',
    example: 'IF ($_NUMLOCK_ON == 0)\n    NUMLOCK\nEND_IF',
  },
  {
    name: '$_SCROLLLOCK_ON',
    type: 'System Variable',
    desc: '1 if Scroll Lock is on, otherwise 0.',
    example: 'PRINT Scroll lock: $_SCROLLLOCK_ON',
  },
  {
    name: '$_BSSID',
    type: 'System Variable',
    desc: 'MAC address of the Wi-Fi board (if Wi-Fi available).',
    example: 'STRING BSSID: $_BSSID',
  },
  {
    name: '$_SSID',
    type: 'System Variable',
    desc: 'Configured Wi-Fi SSID (from config.json).',
    example: 'PRINT SSID: $_SSID',
  },
  {
    name: '$_PASSWD',
    type: 'System Variable',
    desc: 'Wi-Fi password (from config).',
    example: 'PRINT $_PASSWD',
  },
  {
    name: '$_CURRENT_VID',
    type: 'System Variable',
    desc: 'Current USB vendor ID (hex string).',
    example: 'PRINT VID: $_CURRENT_VID',
  },
  {
    name: '$_CURRENT_PID',
    type: 'System Variable',
    desc: 'Current USB product ID (hex string).',
    example: 'PRINT PID: $_CURRENT_PID',
  },
  {
    name: '$_CURRENT_MANF',
    type: 'System Variable',
    desc: 'Current USB manufacturer string.',
    example: 'PRINT Manufacturer: $_CURRENT_MANF',
  },
  {
    name: '$_CURRENT_PROD',
    type: 'System Variable',
    desc: 'Current USB product string.',
    example: 'PRINT Product: $_CURRENT_PROD',
  },

  {
    name: '$_RANDOM_INT',
    type: 'Random Variable',
    desc: 'Random integer between $_RANDOM_MIN and $_RANDOM_MAX.',
    example: 'VAR $r = $_RANDOM_INT\nPRINT Random: $r',
  },
  {
    name: '$_RANDOM_NUMBER',
    type: 'Random Variable',
    desc: 'Random digit string. Use :N for length.',
    example: 'STRING Code: $_RANDOM_NUMBER:6',
  },
  {
    name: '$_RANDOM_LOWERCASE_LETTER',
    type: 'Random Variable',
    desc: 'Random lowercase letter(s). Use :N for count.',
    example: 'STRING lower: $_RANDOM_LOWERCASE_LETTER:4',
  },
  {
    name: '$_RANDOM_UPPERCASE_LETTER',
    type: 'Random Variable',
    desc: 'Random uppercase letter(s).',
    example: 'STRING upper: $_RANDOM_UPPERCASE_LETTER:2',
  },
  {
    name: '$_RANDOM_LETTER',
    type: 'Random Variable',
    desc: 'Random mixed-case letter(s).',
    example: 'STRING mixed: $_RANDOM_LETTER:8',
  },
  {
    name: '$_RANDOM_SPECIAL',
    type: 'Random Variable',
    desc: 'Random special character(s).',
    example: 'STRING special: $_RANDOM_SPECIAL:3',
  },
  {
    name: '$_RANDOM_CHAR',
    type: 'Random Variable',
    desc: 'Random printable character(s).',
    example: 'STRING password: $_RANDOM_CHAR:12',
  },
  {
    name: '$_RANDOM_MIN',
    type: 'Random Variable',
    desc: 'Lower bound for $_RANDOM_INT (default 0).',
    example: '$_RANDOM_MIN = 1000',
  },
  {
    name: '$_RANDOM_MAX',
    type: 'Random Variable',
    desc: 'Upper bound for $_RANDOM_INT (default 65535).',
    example: '$_RANDOM_MAX = 9999',
  },

  {
    name: 'US',
    type: 'Layout',
    desc: 'US keyboard layout.',
    example: 'SELECT_LAYOUT US',
  },
  {
    name: 'US_DVO',
    type: 'Layout',
    desc: 'US Dvorak layout.',
    example: 'SELECT_LAYOUT US_DVO',
  },
  {
    name: 'WIN_FR',
    type: 'Layout',
    desc: 'Windows French layout.',
    example: 'SELECT_LAYOUT WIN_FR\nSTRING Bonjour !',
  },
  {
    name: 'WIN_DE',
    type: 'Layout',
    desc: 'Windows German layout.',
    example: 'SELECT_LAYOUT WIN_DE\nSTRING öäüÖÄÜß',
  },
  {
    name: 'WIN_ES',
    type: 'Layout',
    desc: 'Windows Spanish layout.',
    example: 'SELECT_LAYOUT WIN_ES\nSTRING ¡Hola!',
  },
  {
    name: 'WIN_IT',
    type: 'Layout',
    desc: 'Windows Italian layout.',
    example: 'SELECT_LAYOUT WIN_IT\nSTRING Ciao!',
  },
  {
    name: 'WIN_BR',
    type: 'Layout',
    desc: 'Windows Brazilian Portuguese.',
    example: 'SELECT_LAYOUT WIN_BR\nSTRING Olá!',
  },
  {
    name: 'WIN_CZ',
    type: 'Layout',
    desc: 'Windows Czech layout.',
    example: 'SELECT_LAYOUT WIN_CZ\nSTRING Ahoj!',
  },
  {
    name: 'WIN_CZ1',
    type: 'Layout',
    desc: 'Windows Czech (alternative).',
    example: 'SELECT_LAYOUT WIN_CZ1',
  },
  {
    name: 'WIN_DA',
    type: 'Layout',
    desc: 'Windows Danish layout.',
    example: 'SELECT_LAYOUT WIN_DA\nSTRING Hej!',
  },
  {
    name: 'WIN_HU',
    type: 'Layout',
    desc: 'Windows Hungarian layout.',
    example: 'SELECT_LAYOUT WIN_HU\nSTRING Szia!',
  },
  {
    name: 'WIN_PO',
    type: 'Layout',
    desc: 'Windows Polish layout.',
    example: 'SELECT_LAYOUT WIN_PO\nSTRING Cześć!',
  },
  {
    name: 'WIN_SW',
    type: 'Layout',
    desc: 'Windows Swedish layout.',
    example: 'SELECT_LAYOUT WIN_SW\nSTRING Hej!',
  },
  {
    name: 'WIN_TR',
    type: 'Layout',
    desc: 'Windows Turkish layout.',
    example: 'SELECT_LAYOUT WIN_TR\nSTRING Merhaba!',
  },
  {
    name: 'WIN_UK',
    type: 'Layout',
    desc: 'Windows United Kingdom layout.',
    example: 'SELECT_LAYOUT WIN_UK\nSTRING £',
  },
  {
    name: 'MAC_FR',
    type: 'Layout',
    desc: 'Mac French layout.',
    example: 'SELECT_LAYOUT MAC_FR\nSTRING Bonjour !',
  },

  {
    name: 'LEFT',
    type: 'Mouse Button',
    desc: 'Left mouse button.',
    example: 'MOUSE_CLICK LEFT',
  },
  {
    name: 'RIGHT',
    type: 'Mouse Button',
    desc: 'Right mouse button.',
    example: 'MOUSE_CLICK RIGHT',
  },
  {
    name: 'MIDDLE',
    type: 'Mouse Button',
    desc: 'Middle mouse button.',
    example: 'MOUSE_CLICK MIDDLE',
  },
];
